# Pandas 

Built on top of NumPy, but designed for real-world, labeled, messy data — like a spreadsheet living inside Python. Where NumPy gives you raw numerical arrays, Pandas gives you rows and columns with names, and tools built specifically for cleaning and reshaping that kind of data.

The two core structures

1. Series — a single column. One-dimensional, labeled (each value has an index, not just a position). Think of it as one column of a spreadsheet, with row labels attached.

2. DataFrame — a full table. Two-dimensional: rows and columns, where every column is technically a Series, and all columns share the same row index. This is what you'll work with 95% of the time — it is your dataset once loaded.

## 1. Importing Pandas

Theory: Pandas is almost always imported with the alias pd — it's the universal convention, so every tutorial, Stack Overflow answer, and teammate's code will use it too.

In [1]:
import pandas as pd

## 2. Series — a single labeled column

A Series is a 1D array with an attached index (labels for each value). Unlike a plain NumPy array, you can access values by label, not just position.

In [ ]:
s = pd.Series([10,20,25,30] , index =["a","b","c","d"])
print(f"get series(col) with thier index as mentioned :\n {s}")

print(f"\n using index, call specific series element such as c: {s["c"]}") # access by label → 20

get series(col) with thier index as mentioned :
 a    10
b    20
c    25
d    30
dtype: int64

 using index, call specific series element such as c: 25

## 3.  DataFrame — the full table

A DataFrame is 2D — rows and columns, where each column is a Series. You'll create one manually here just to see the structure, but in real work you almost always load one from a file.

In [10]:
data =  {
    "names"  : ["ab","salam","lakhan","khan"],
    "f_subs" : ["math","science","phyics","chemistry"],
    "stack"  : ["Python","Fastapi","git","DB"]
}
df = pd.DataFrame(data)
print(df)

    names     f_subs    stack
0      ab       math   Python
1   salam    science  Fastapi
2  lakhan     phyics      git
3    khan  chemistry       DB

## 4. Reading a CSV — read_csv()

This is how you load a real dataset. Pandas reads the file and automatically infers column names (from the header row) and data types per column — the file becomes a DataFrame in one line.

In [ ]:
# python
df = pd.read_csv("data/telco_churn.csv")

## 5. First look — .head() and .tail()

The very first thing you do after loading any dataset — a quick peek at the top/bottom rows to sanity-check the data looks like what you expect, before doing anything else.

In [11]:
print(df.head())

    names     f_subs    stack
0      ab       math   Python
1   salam    science  Fastapi
2  lakhan     phyics      git
3    khan  chemistry       DB

In [ ]:
print(df.tail(2)) # tail helps to get access from last

    names     f_subs stack
2  lakhan     phyics   git
3    khan  chemistry    DB

## 6. Shape and basic structure — .shape, .columns, .info()

.shape tells you rows × columns. .columns lists column names. .info() is the most useful of the three — it shows every column's data type and how many non-null values it has, which is exactly how you catch a numeric column secretly stored as text.

In [ ]:
print(df.shape) # 4 rows , 3 cols

(4, 3)

In [17]:
print(df.columns)

Index(['names', 'f_subs', 'stack'], dtype='str')

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   4 non-null      str
 1   f_subs  4 non-null      str
 2   stack   4 non-null      str
dtypes: str(3)
memory usage: 228.0 bytes

In [53]:
print(len(df))

5

In [58]:
df["Rating"] = [0.6, 0.8, 0.4, 0.5, 0.6]
df["Progress"] = ["good"," "," "," ","expert"]
df["Backend"]  = ["python","django"," ","fastapi","flask"]
print(df)

      names     f_subs    stack  Rating Progress  Backend
0        ab       math   Python     0.6     good   python
1     salam    science  Fastapi     0.8            django
2    lakhan     phyics      git     0.4
3  khanshab  chemistry       DB     0.5           fastapi
4        ab       math   Python     0.6   expert    flask

## 7. Summary statistics - .describe()

One command that gives you count, mean, std dev, min, max, and quartiles for every numeric column at once - the fastest way to spot obvious outliers or weird ranges before diving into detailed EDA.

In [41]:
df.describe()

         Rating
count  4.000000
mean   0.575000
std    0.170783
min    0.400000
25%    0.475000
50%    0.550000
75%    0.650000
max    0.800000

In [42]:
df[df["Rating"]>0.5]

   names   f_subs    stack  Rating Progress Backend
0     ab     math   Python     0.6     good  python
1  salam  science  Fastapi     0.8           django

In [44]:
df.loc[3,"names"] = "khanshab"
# df.loc[2, "age"] = 28

print(df["names"])

0          ab
1       salam
2      lakhan
3    khanshab
Name: names, dtype: str

In [45]:
df.isnull()

   names  f_subs  stack  Rating  Progress  Backend
0  False   False  False   False     False    False
1  False   False  False   False     False    False
2  False   False  False   False     False    False
3  False   False  False   False     False    False

In [59]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [60]:
df.loc[4] = df.loc[0]   # copies row 0 exactly into a new row 4
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [72]:
df

      names     f_subs    stack  Rating Progress  Backend
0        ab       math   Python     0.6     good   python
1     salam    science  Fastapi     0.8            django
2    lakhan     phyics      git     0.4
3  khanshab  chemistry       DB     0.5           fastapi
4        ab       math   Python     0.6     good   python

In [75]:
df["Progress"] = df["Progress"].replace(" ", np.nan)
df["Backend"] = df["Backend"].replace(" ", np.nan)
df

      names     f_subs    stack  Rating Progress  Backend
0        ab       math   Python     0.6     good   python
1     salam    science  Fastapi     0.8      NaN   django
2    lakhan     phyics      git     0.4      NaN      NaN
3  khanshab  chemistry       DB     0.5      NaN  fastapi
4        ab       math   Python     0.6     good   python

In [67]:
import numpy as np

demo = pd.DataFrame({
    "id": [1, 2, 1, 4],
    "name": ["Ali", "Sara", "Ali", "John"],
    "score": [85, np.nan, 85, 90],
    "city": ["Karachi", "Lahore", "Karachi", None]
})
print(demo)

   id  name  score     city
0   1   Ali   85.0  Karachi
1   2  Sara    NaN   Lahore
2   1   Ali   85.0  Karachi
3   4  John   90.0      NaN

In [68]:
print(demo.duplicated())

0    False
1    False
2     True
3    False
dtype: bool

In [70]:
demo.isnull()

      id   name  score   city
0  False  False  False  False
1  False  False   True  False
2  False  False  False  False
3  False  False  False   True

In [71]:
print(demo.isnull().sum())

id       0
name     0
score    1
city     1
dtype: int64

In [78]:
messy = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "charges": ["100.5", "200", " ", "150.75"]
})
print(messy.dtypes)   # charges is 'object' (text), not numeric

messy["charges"] = pd.to_numeric(messy["charges"], errors="coerce")
print(messy)
print("\n messy \n ",messy.dtypes)   # now float64

id         int64
charges      str
dtype: object
   id  charges
0   1   100.50
1   2   200.00
2   3      NaN
3   4   150.75

 messy
  id           int64
charges    float64
dtype: object